import Link from 'next/link';
import {ArrowUpRight,Route,LifeBuoy,SlidersHorizontal} from 'lucide-react';
import {PuduIntro,PuduCTA} from './PuduSections';
import {localPath,type Locale} from '@/lib/locale';
import {supportFaqs} from '@/lib/support-guide';
import SolutionFinder from './SolutionFinder';
import SupportRequest from './SupportRequest';
import ROICalculator from './ROICalculator';
import BreadcrumbSchema from './BreadcrumbSchema';
import {puduProducts} from '@/lib/pudu';
import {site} from '@/lib/site';
function PageSchema({path,name,locale}:{path:string;name:string;locale:Locale}){return <BreadcrumbSchema items={[{name:locale==='es'?'Inicio':'Home',url:localPath('/',locale)},{name,url:localPath(path,locale)}]}/>;}
export function DecisionHub({locale='es'}:{locale?:Locale}){
 const es=locale==='es';return <section className="decision-hub section-space"><div className="container-x"><div className="section-heading-row"><div><p className="eyebrow">{es?'DE LA CURIOSIDAD A LA DECISIÓN':'FROM CURIOSITY TO A DECISION'}</p><h2>{es?'Un buen robot empieza':'The right robot starts'}<br/>{es?'con una buena pregunta.':'with the right question.'}</h2></div><p className="section-side-copy">{es?'Aclara tu tarea, prepara la implementación y encuentra acompañamiento en un mismo lugar.':'Clarify your task, prepare implementation and find support in one place.'}</p></div><div className="decision-cards">{[
 {icon:SlidersHorizontal,path:'/encuentra-tu-robot',title:es?'¿Cuál es para mí?':'Which one fits?',text:es?'Elige una tarea y descubre modelos para evaluar con nuestro equipo.':'Choose a task and discover models to assess with our team.',cta:es?'Encontrar mi robot':'Find my robot'},
 {icon:Route,path:'/preguntas-frecuentes',title:es?'¿Cómo empiezo?':'How do I start?',text:es?'Renta, compra, demostración, cobertura y preparación del espacio.':'Rental, purchase, demonstrations, coverage and site preparation.',cta:es?'Resolver mis dudas':'Get answers'},
 {icon:LifeBuoy,path:'/soporte',title:es?'Mi robot ya trabaja.':'My robot is at work.',text:es?'Prepara una consulta de soporte, mantenimiento o refacciones.':'Prepare a request for support, maintenance or spare parts.',cta:es?'Ir a soporte':'Go to support'},
 ].map(({icon:Icon,...c})=><Link key={c.path} href={localPath(c.path,locale)}><Icon size={27}/><h3>{c.title}</h3><p>{c.text}</p><span className="text-link">{c.cta}<ArrowUpRight size={18}/></span></Link>)}</div></div></section>;
}
export function FinderPage({locale='es'}:{locale?:Locale}){const es=locale==='es';return <><PuduIntro locale={locale} eyebrow={es?'Encuentra tu robot':'Find your robot'} title={es?'Tu tarea. Tu espacio. Tu siguiente robot.':'Your task. Your space. Your next robot.'} description={es?'Explora robots para tu empresa en México y prepara una conversación concreta con Botmate. Empieza por lo que quieres resolver.':'Explore robots for your business in Mexico and prepare a focused conversation with Botmate. Start with what you want to solve.'}/><SolutionFinder locale={locale} products={puduProducts.map(({slug,name,image,category})=>({slug,name,image,category}))}/><ROICalculator locale={locale}/><PageSchema locale={locale} path="/encuentra-tu-robot" name={es?'Encuentra tu robot':'Find your robot'}/></>;}
export function FAQPage({locale='es'}:{locale?:Locale}){const es=locale==='es';return <><PuduIntro locale={locale} eyebrow={es?'Preguntas frecuentes':'Frequently asked questions'} title={es?'Decide con claridad.':'Make an informed decision.'} description={es?'Respuestas para preparar una renta, compra, demostración o implementación de robots en México con Botmate.':'Answers to help prepare a robot rental, purchase, demonstration or implementation in Mexico with Botmate.'}/><section className="container-x faq-hub"><div className="faq-hub-list">{supportFaqs.map((f,i)=><details key={i}><summary><span>{String(i+1).padStart(2,'0')}</span>{f.q[locale]}<span className="faq-plus" aria-hidden="true">+</span></summary><p>{f.a[locale]}</p></details>)}</div><aside className="faq-next"><p className="eyebrow">{es?'TU SIGUIENTE PASO':'YOUR NEXT STEP'}</p><h2>{es?'De la pregunta al proyecto.':'From question to project.'}</h2><p>{es?'Elige la tarea que quieres resolver y lleva tus primeras opciones a una llamada.':'Choose the task you want to solve and bring your first options to a call.'}</p><Link href={localPath('/encuentra-tu-robot',locale)} className="btn-primary">{es?'Explorar opciones':'Explore options'}<ArrowUpRight size={18}/></Link><Link href={localPath('/soporte',locale)} className="text-link">{es?'Necesito soporte':'I need support'}<ArrowUpRight size={17}/></Link></aside></section><PuduCTA locale={locale}/><PageSchema locale={locale} path="/preguntas-frecuentes" name={es?'Preguntas frecuentes':'Frequently asked questions'}/></>;}
export function SupportPage({locale='es'}:{locale?:Locale}){const es=locale==='es';return <><PuduIntro locale={locale} eyebrow={es?'Soporte Botmate':'Botmate support'} title={es?'Tu operación sigue siendo el centro.':'Your operation stays at the center.'} description={es?'Un punto de partida para diagnóstico, mantenimiento, capacitación y refacciones de robots en México. Cuéntanos qué equipo tienes y qué necesitas resolver.':'A starting point for diagnosis, maintenance, training and robot spare parts in Mexico. Tell us which unit you have and what you need to solve.'}/><section className="container-x support-layout"><SupportRequest locale={locale}/><aside className="support-aside"><p className="eyebrow">{es?'ANTES DE ESCRIBIRNOS':'BEFORE YOU CONTACT US'}</p><h2>{es?'El detalle ayuda.':'Details help.'}</h2><ol>{(es?['Identifica el modelo y número de serie.','Anota el error y las condiciones en que aparece.','Prepara una foto de la pantalla o de la pieza.','Indica ciudad y disponibilidad para revisar el equipo.']:['Identify the model and serial number.','Note the error and when it occurs.','Prepare a photo of the screen or part.','Share your city and availability for assessment.']).map(t=><li key={t}>{t}</li>)}</ol><p>{es?'La respuesta, visita, garantía, disponibilidad de piezas y costos se acuerdan con el equipo según el diagnóstico y las condiciones de tu propuesta.':'Response, visits, warranty, parts availability and costs are agreed with the team based on diagnosis and your proposal terms.'}</p><a className="text-link" href={'mailto:'+site.email}>{site.email}<ArrowUpRight size={16}/></a><Link className="text-link" href={localPath('/refacciones',locale)}>{es?'Explorar accesorios por modelo':'Explore accessories by model'}<ArrowUpRight size={16}/></Link><Link className="text-link" href={localPath('/reservar',locale)}>{es?'Estoy evaluando un proyecto nuevo':'I am evaluating a new project'}<ArrowUpRight size={16}/></Link></aside></section><section className="container-x support-process section-space"><p className="eyebrow">{es?'ACOMPAÑAMIENTO, PASO A PASO':'SUPPORT, STEP BY STEP'}</p><div className="pudu-service-grid">{(es?[['01','Entender','Recopilamos el contexto del equipo y la necesidad para orientar la revisión.'],['02','Acordar','Definimos diagnóstico, alcance, compatibilidad, costo y siguiente paso aplicable.'],['03','Dar seguimiento','La atención y su cierre se coordinan con el responsable de tu operación.']]:[['01','Understand','We gather context about the unit and your needs to guide the assessment.'],['02','Agree','We define diagnosis, scope, compatibility, cost and the applicable next step.'],['03','Follow up','Service and closure are coordinated with the person responsible for your operation.']]).map(([n,t,p])=><article key={n}><span className="eyebrow">{n}</span><h2>{t}</h2><p>{p}</p></article>)}</div></section><PageSchema locale={locale} path="/soporte" name={es?'Soporte':'Support'}/></>;}
