'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import { Search, ArrowUpRight, X } from 'lucide-react';
import { puduProducts, familyNames } from '@/lib/pudu';
import { localPath, type Locale } from '@/lib/locale';
export default function PuduCatalog({locale='es',initialCategory='all'}:{locale?:Locale;initialCategory?:string}) {
 const [category,setCategory]=useState(familyNames[initialCategory]?initialCategory:"all"),[query,setQuery]=useState(''),[selected,setSelected]=useState<string[]>([]);const es=locale==='es';
 const normalize=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const list=puduProducts.filter(r=>(category==='all'||r.category===category)&&normalize(r.name+' '+r.description[locale]+' '+familyNames[r.category][locale]).includes(normalize(query)));
 const compare=puduProducts.filter(r=>selected.includes(r.slug));
 return <><div className="pudu-catalog-tools"><div className="filter-tabs" role="group" aria-label={es?'Familia de robots':'Robot family'}>{['all',...Object.keys(familyNames)].map(c=><button type="button" key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c==='all'?(es?'Todos':'All'):familyNames[c][locale]}</button>)}</div><label className="catalog-search"><Search size={18}/><span className="sr-only">{es?'Buscar modelos':'Search models'}</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={es?'Busca tu robot':'Find your robot'}/></label></div>
 <p className="result-count" aria-live="polite">{list.length} {es?'modelos y variantes · Compara hasta 3':'models and variants · Compare up to 3'}</p>
 <div className="pudu-product-grid">{list.map(r=><article className="pudu-product-card" key={r.slug}><Link href={localPath('/robots/'+r.slug,locale)}><div className="pudu-product-photo">{r.new&&<span className="new-product">{es?'NUEVO':'NEW'}</span>}<Image src={r.image} alt={r.name} fill sizes="(min-width: 1100px) 30vw, (min-width: 650px) 46vw, 90vw"/></div><div className="pudu-card-copy"><span className="tiny-label">{familyNames[r.category][locale]}</span><h2>{r.name}<ArrowUpRight size={22}/></h2><p>{r.description[locale]}</p></div></Link><label className="pudu-compare"><input type="checkbox" checked={selected.includes(r.slug)} disabled={!selected.includes(r.slug)&&selected.length===3} onChange={()=>setSelected(v=>v.includes(r.slug)?v.filter(s=>s!==r.slug):[...v,r.slug])}/>{es?'Comparar':'Compare'}<span className="sr-only"> {r.name}</span></label></article>)}</div>
 {!list.length&&<div className="empty-state"><h2>{es?'Prueba con otro modelo.':'Try another model.'}</h2><button className="btn-ghost" onClick={()=>{setQuery('');setCategory('all')}}>{es?'Restablecer filtros':'Reset filters'}</button></div>}
 {!!compare.length&&<section className="comparison-panel"><div className="section-heading-row"><h2>{es?'Tu selección, lado a lado.':'Your selection, side by side.'}</h2><button className="btn-ghost" onClick={()=>setSelected([])}>{es?'Limpiar':'Clear'}<X size={16}/></button></div><div className="table-scroll" role="region" tabIndex={0} aria-label={es?'Comparación de robots':'Robot comparison'}><table><caption>{es?'Aplicaciones y características publicadas por Pudu':'Applications and features published by Pudu'}</caption><thead><tr><th scope="col">{es?'Modelo':'Model'}</th>{compare.map(r=><th key={r.slug} scope="col">{r.name}</th>)}</tr></thead><tbody><tr><th scope="row">{es?'Familia':'Family'}</th>{compare.map(r=><td key={r.slug}>{familyNames[r.category][locale]}</td>)}</tr><tr><th scope="row">{es?'Aplicación':'Application'}</th>{compare.map(r=><td key={r.slug}>{r.description[locale]}</td>)}</tr><tr><th scope="row">{es?'Características':'Features'}</th>{compare.map(r=><td key={r.slug}>{r.features[locale].slice(0,3).join(' · ')}</td>)}</tr><tr><th scope="row">{es?'Explorar':'Explore'}</th>{compare.map(r=><td key={r.slug}><Link className="text-link" href={localPath('/robots/'+r.slug,locale)}>{es?'Ver ficha':'View details'}<ArrowUpRight size={15}/></Link></td>)}</tr></tbody></table></div></section>}
 </>
}
