import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, ArrowRight } from 'lucide-react';
import { puduProducts,puduIndustries,puduLogos,familyNames,type PuduProduct } from '@/lib/pudu';
import stories from '@/lib/pudu-stories.json';
import { localPath,type Locale } from '@/lib/locale';
import PuduHero from './PuduHero';
import ExperienceCinema from './ExperienceCinema';
import {HomeAreas,HomeCases,HomeNext} from './HomeSections';
import CinematicMedia from './CinematicMedia';
import RobotProductPage from './RobotProductPage';
export function PuduCTA({locale='es'}:{locale?:Locale}){const es=locale==='es';return <section className="pudu-cta"><div className="container-x"><p className="eyebrow">{es?'TU PRÓXIMO PASO':'YOUR NEXT STEP'}</p><h2>{es?'El futuro de tu operación':'The future of your operation'}<br/><span>{es?'empieza con una conversación.':'starts with a conversation.'}</span></h2><Link href={localPath('/reservar',locale)} className="btn-primary">{es?'Reserva una llamada':'Book a call'}<ArrowUpRight size={19}/></Link><p>{es?'30 minutos · Google Meet · Agenda de Botmate':'30 minutes · Google Meet · Botmate calendar'}</p></div></section>}
export function PuduIntro({locale='es',eyebrow,title,description}:{locale?:Locale;eyebrow:string;title:string;description:string}){return <section className="pudu-intro container-x"><Link className="pudu-breadcrumb" href={localPath('/',locale)}>Botmate <span>/</span> {eyebrow}</Link><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="pudu-intro-description">{description}</p></section>}
export function PuduTrust({locale='es',all=false}:{locale?:Locale;all?:boolean}){const es=locale==='es';const logos=all?puduLogos:puduLogos.filter(x=>['Marriott','Walmart México y Centroamérica','Pepsi','Coca-Cola','Panasonic','MediaMarkt','Pizza Hut','Shell'].includes(x.name));return <section className="pudu-trust section-space"><div className="container-x"><div className="section-heading-row"><div><p className="eyebrow">{es?'EL ALCANCE DE NUESTRO FABRICANTE':'OUR MANUFACTURER’S GLOBAL REACH'}</p><h2>{es?'Tecnología que ya está':'Technology already at work'}<br/>{es?'en el mundo.':'around the world.'}</h2></div><p className="section-side-copy">{es?'Marcas que Pudu Robotics presenta en su red de clientes y aplicaciones internacionales.':'Brands featured by Pudu Robotics in its international customer and application network.'}</p></div><div className="pudu-logo-grid">{logos.map(l=><div key={l.image} className="pudu-logo-cell"><Image src={l.image} alt={l.name} width={180} height={90}/></div>)}</div><p className="pudu-attribution">{es?'Referencias publicadas por Pudu Robotics. Estos logos no representan clientes, contratos ni avales directos de Botmate.':'References published by Pudu Robotics. These logos do not represent direct Botmate customers, contracts or endorsements.'}</p>{!all&&<Link href={localPath('/nosotros',locale)+'#respaldo'} className="text-link">{es?'Conoce el respaldo internacional':'Explore the international network'}<ArrowRight size={18}/></Link>}</div></section>}
export function PuduStats({locale='es'}:{locale?:Locale}){const es=locale==='es';return <section className="pudu-stats"><div className="container-x"><p className="eyebrow">PUDU ROBOTICS / {es?'ESCALA GLOBAL':'GLOBAL SCALE'}</p><div className="pudu-stats-grid">{[['130,000+',es?'Unidades enviadas globalmente':'Units shipped globally'],['85+',es?'Países y regiones':'Countries and regions'],['1,000+',es?'Centros de servicio globales':'Global service centers']].map(([n,l])=><div key={l}><strong>{n}</strong><p>{l}</p></div>)}</div><p className="pudu-attribution">{es?'Cifras globales reportadas por Pudu Robotics, consultadas el 13 de septiembre de 2026. No corresponden a la operación de Botmate.':'Global figures reported by Pudu Robotics, accessed September 13, 2026. These are not Botmate operating figures.'}</p></div></section>}
export function PuduIndustries({locale='es',compact=false}:{locale?:Locale;compact?:boolean}){const es=locale==='es';const list=compact?puduIndustries.slice(0,6):puduIndustries;return <section className="section-space"><div className="container-x"><div className="section-heading-row"><div><p className="eyebrow">{es?'DISEÑADO PARA TU INDUSTRIA':'BUILT FOR YOUR INDUSTRY'}</p><h2>{es?'Un mundo de aplicaciones.':'A world of applications.'}</h2></div>{compact&&<Link href={localPath('/sectores',locale)} className="text-link">{es?'Explorar 11 áreas':'Explore 11 application areas'}<ArrowUpRight size={18}/></Link>}</div><div className="pudu-industry-grid">{list.map((r,i)=><Link key={r.slug} href={localPath('/sectores/'+r.slug,locale)} className="pudu-industry-card"><div className="pudu-industry-photo"><Image src={r.image} alt={r.title[locale]+' · Pudu Robotics'} fill sizes="(min-width: 1000px) 32vw, (min-width: 650px) 47vw, 92vw"/></div><span>{String(i+1).padStart(2,'0')} / {es?'SOLUCIONES':'SOLUTIONS'}</span><h3>{r.title[locale]}<ArrowUpRight size={20}/></h3></Link>)}</div></div></section>}
export function PuduCaseCards({locale='es',compact=false}:{locale?:Locale;compact?:boolean}){const es=locale==='es';const list=compact?stories.cases.filter(c=>['mediamarkt','skylark','parkhotel'].includes(c.slug)):stories.cases;return <section className="section-space pudu-case-section"><div className="container-x"><div className="section-heading-row"><div><p className="eyebrow">{es?'CASOS INTERNACIONALES DE PUDU':'PUDU INTERNATIONAL CASE STUDIES'}</p><h2>{es?'En lugares como el tuyo.':'In places like yours.'}</h2></div>{compact&&<Link className="text-link" href={localPath('/casos-de-exito',locale)}>{es?'Todos los casos':'All case studies'}<ArrowUpRight size={18}/></Link>}</div><div className="pudu-case-grid">{list.map(c=><Link href={localPath('/casos-de-exito/'+c.slug,locale)} key={c.slug} className="pudu-case-card"><div className="pudu-case-photo"><Image src={c.image} alt={c.brand+' · '+c.country[locale]} fill sizes="(min-width: 1000px) 31vw, 93vw"/></div><div><p className="tiny-label">{c.country[locale]} · PUDU ROBOTICS</p><h3>{c.brand}<ArrowUpRight size={20}/></h3><p>{c.title[locale]}</p></div></Link>)}</div><p className="pudu-attribution">{es?'Experiencias documentadas por Pudu Robotics en otros mercados. Los resultados de cada instalación dependen de su contexto.':'Experiences documented by Pudu Robotics in other markets. Installation outcomes depend on their individual context.'}</p></div></section>}
export function PuduTestimonials({locale='es'}:{locale?:Locale}){const es=locale==='es';return <section className="section-space"><div className="container-x"><div className="section-heading-row"><div><p className="eyebrow">{es?'VOCES DE LA RED PUDU':'VOICES FROM THE PUDU NETWORK'}</p><h2>{es?'La experiencia de quienes':'Hear from the people'}<br/>{es?'conviven con los robots.':'working alongside robots.'}</h2></div><p className="section-side-copy">{es?'Síntesis de testimonios publicados por el fabricante. Desliza para explorar.':'Summaries of testimonials published by the manufacturer. Scroll to explore.'}</p></div><div className="pudu-testimonial-track" tabIndex={0} role="region" aria-label={es?'Testimonios de clientes de Pudu':'Pudu customer testimonials'}>{stories.testimonials.map(t=><article className="pudu-testimonial" key={t.brand}><Image src={t.image} alt={t.brand} width={560} height={340}/><div><span className="pudu-quote-mark" aria-hidden="true">“</span><p>{t.text[locale]}</p><strong>{es?t.brand.replace("Poland","Polonia").replace("Spain","España").replace("in Japan","en Japón").replace("Japan","Japón"):t.brand}</strong><Link href={localPath("/casos-de-exito",locale)}>{es?"Explorar casos en Botmate":"Explore cases on Botmate"} ↗</Link></div></article>)}</div><p className="pudu-attribution">{es?'Resúmenes editoriales, no citas textuales ni reseñas de Botmate.':'Editorial summaries, not direct quotes or reviews of Botmate.'}</p></div></section>}
export function PuduProductTile({robot:r,locale='es'}:{robot:PuduProduct;locale?:Locale}){return <Link href={localPath('/robots/'+r.slug,locale)} className="pudu-product-card"><div className="pudu-product-photo"><Image src={r.image} alt={r.name} fill sizes="(min-width: 1000px) 30vw, 90vw"/></div><div className="pudu-card-copy"><span className="tiny-label">{familyNames[r.category][locale]}</span><h3>{r.name}<ArrowUpRight size={22}/></h3><p>{r.description[locale]}</p></div></Link>}
export function PuduShowcase({locale='es'}:{locale?:Locale}){const es=locale==='es';const models=['pudu-cc1-pro','pudu-t600','pudu-d5-series'];return <section className="section-space pudu-official-showcase"><div className="container-x"><div className="section-heading-row"><div><p className="eyebrow">PUDU / {es?'EN MOVIMIENTO':'IN MOTION'}</p><h2>{es?'La ingeniería cobra vida.':'Engineering comes to life.'}</h2></div><p className="section-side-copy">{es?'Secuencias oficiales del fabricante. Conoce la tecnología desde adentro.':'Official manufacturer sequences. Take a closer look at the technology.'}</p></div><div className="pudu-showcase-grid">{models.map(slug=>{const r=puduProducts.find(r=>r.slug===slug)!;return <article key={slug}><CinematicMedia poster={r.poster||r.image} src={r.video} alt={r.name+' · Pudu Robotics'} locale={locale}/><Link href={localPath('/robots/'+r.slug,locale)}><span>{r.name}</span><ArrowUpRight size={20}/></Link></article>})}</div><p className="pudu-attribution">{es?'Extractos oficiales sin audio. Las demostraciones de IA física pueden incluir funciones en desarrollo.':'Official excerpts without audio. Physical AI demonstrations may include features under development.'}</p></div></section>}
export function PuduHome({locale='es'}:{locale?:Locale}) {
  return <div className="compact-home"><PuduHero locale={locale}/><HomeAreas locale={locale}/><ExperienceCinema locale={locale}/><HomeCases locale={locale}/><HomeNext locale={locale}/></div>;
}
export function PuduProductDetail({robot,locale='es'}:{robot:PuduProduct;locale?:Locale}){return <RobotProductPage robot={robot} locale={locale}/>;}
