'use client';
import {useState} from 'react';
import {estimateWorkload} from '@/lib/operation-estimate.mjs';
import {waLink} from '@/lib/site';
import type {Locale} from '@/lib/locale';
import {ArrowUpRight} from 'lucide-react';
export default function ROICalculator({locale='es'}:{locale?:Locale}){
 const es=locale==='es';const [trips,setTrips]=useState(60),[minutes,setMinutes]=useState(3),[days,setDays]=useState(22),[share,setShare]=useState(50);
 const result=estimateWorkload(trips,minutes,days,share)!;const fmt=(n:number)=>n.toLocaleString(es?'es-MX':'en-US',{maximumFractionDigits:1});
 const inputs=[{label:es?'Recorridos por día':'Trips per day',value:trips,set:setTrips,min:0,max:500,step:5},{label:es?'Minutos por recorrido':'Minutes per trip',value:minutes,set:setMinutes,min:0.5,max:30,step:0.5},{label:es?'Días de operación al mes':'Operating days per month',value:days,set:setDays,min:1,max:31,step:1},{label:es?'Porcentaje de recorridos a evaluar':'Share of trips to evaluate',value:share,set:setShare,min:0,max:100,step:5}];
 const message=es?`Hola Botmate, quiero evaluar una operación de ${trips} recorridos/día, ${minutes} min/recorrido y ${days} días/mes. Quiero estudiar ${share}% de los recorridos (${fmt(result.reviewHours)} horas actuales/mes). Es un escenario de carga de trabajo, no ahorro comprobado.`:`Hello Botmate, I want to assess an operation with ${trips} trips/day, ${minutes} min/trip and ${days} days/month. I want to study ${share}% of trips (${fmt(result.reviewHours)} current hours/month). This is a workload scenario, not verified savings.`;
 return <section className="section-space workload-section"><div className="container-x"><div className="section-heading-row"><div><p className="eyebrow">{es?'DIMENSIONA TU OPERACIÓN':'SIZE UP YOUR OPERATION'}</p><h2>{es?'¿Cuánto tiempo ocupa':'How much time goes into'}<br/>{es?'moverse de A a B?':'moving from A to B?'}</h2></div><p className="section-side-copy">{es?'Una primera cuenta para las tareas de transporte. Introduce tus datos o explora el ejemplo; úsalo para decidir qué medir en una prueba.':'A first calculation for transport tasks. Enter your data or explore the example; use it to decide what to measure in a trial.'}</p></div><div className="workload-grid"><div className="workload-inputs">{inputs.map((i,index)=><label key={index}><span>{i.label}<strong>{i.value}{index===3?'%':''}</strong></span><input type="range" min={i.min} max={i.max} step={i.step} value={i.value} onChange={e=>i.set(Number(e.target.value))}/></label>)}</div><div className="workload-result"><p className="tiny-label">{es?'CARGA DE TRABAJO A ESTUDIAR':'WORKLOAD TO STUDY'}</p><output aria-live="polite"><strong>{fmt(result.reviewHours)}</strong><span>{es?'horas actuales / mes':'current hours / month'}</span></output><p>{es?'Sobre un total de':'Out of'} {fmt(result.totalHours)} {es?'horas mensuales de recorrido en este escenario.':'monthly travel hours in this scenario.'}</p><p className="workload-formula">{es?'Recorridos × minutos × días ÷ 60 × porcentaje elegido.':'Trips × minutes × days ÷ 60 × selected share.'}</p><a className="btn-primary" href={waLink(message)} target="_blank" rel="noopener noreferrer">{es?'Llevar este escenario a Botmate':'Discuss this scenario with Botmate'}<ArrowUpRight size={18}/></a><p className="fine-print">{es?'No predice ahorro, rendimiento del robot ni reducción de personal. La prueba debe medir tiempos de carga, supervisión, recarga, esperas e intervenciones. Los valores iniciales son un ejemplo.':'This does not predict savings, robot performance or staffing reductions. A trial must measure loading, supervision, charging, waiting and intervention times. Initial values are an example.'}</p></div></div></div></section>;
}
