'use client';
import {useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {ArrowUpRight,Check} from 'lucide-react';
import {localPath,type Locale} from '@/lib/locale';
import {solutionTasks} from '@/lib/solution-guide';
import {waLink} from '@/lib/site';
export default function SolutionFinder({locale='es',products}:{locale?:Locale;products:{slug:string;name:string;image:string;category:string}[]}){
 const es=locale==='es';const [task,setTask]=useState('industrial');const [city,setCity]=useState('');const [mode,setMode]=useState('evaluate');
 const selected=solutionTasks.find(t=>t.id===task)!;
 const models=products.filter(p=>selected.models?selected.models.includes(p.slug):p.category===selected.category);
 const modes=[['evaluate',es?'Por definir':'To be determined'],['rental',es?'Renta':'Rental'],['purchase',es?'Compra':'Purchase']];
 const message=es?`Hola Botmate, preparé mi proyecto en su sitio. Tarea: ${selected.label.es}. Ciudad: ${city.trim()||'Por definir'}. Modalidad: ${modes.find(m=>m[0]===mode)![1]}. Quiero validar el modelo, el espacio y una demostración.`:`Hello Botmate, I prepared my project on your website. Task: ${selected.label.en}. City: ${city.trim()||'To be determined'}. Option: ${modes.find(m=>m[0]===mode)![1]}. I would like to validate the model, site conditions and a demonstration.`;
 return <section className="container-x solution-finder"><div className="finder-controls"><fieldset><legend><span>01</span>{es?'¿Qué necesitas resolver?':'What do you need to solve?'}</legend><div className="task-options">{solutionTasks.map(t=><label className={'task-option '+(task===t.id?'is-selected':'')} key={t.id}><input type="radio" name="task" value={t.id} checked={task===t.id} onChange={()=>setTask(t.id)}/><span><strong>{t.label[locale]}</strong><small>{t.description[locale]}</small></span>{task===t.id&&<Check size={18} aria-hidden="true"/>}</label>)}</div></fieldset><fieldset><legend><span>02</span>{es?'Dale contexto al proyecto':'Add your project context'}</legend><div className="finder-context"><label>{es?'Ciudad (opcional)':'City (optional)'}<input value={city} maxLength={80} onChange={e=>setCity(e.target.value)} placeholder={es?'¿Dónde operará?':'Where will it operate?'}/></label><label>{es?'Modalidad':'Option'}<select value={mode} onChange={e=>setMode(e.target.value)}>{modes.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div></fieldset></div>
 <div className="finder-results"><div className="finder-result-heading"><span className="eyebrow">{es?'TU PUNTO DE PARTIDA':'YOUR STARTING POINT'}</span><h2>{selected.label[locale]}</h2><p aria-live="polite">{models.length} {es?'modelos para explorar':'models to explore'}</p></div><div className="finder-models">{models.map(p=><Link key={p.slug} href={localPath('/robots/'+p.slug,locale)}><Image src={p.image} alt={p.name} width={220} height={180} sizes="(min-width:800px) 16vw, 40vw"/><strong>{p.name}<ArrowUpRight size={16}/></strong></Link>)}</div><div className="finder-check"><h3>{es?'Lo que validaremos contigo':'What we will validate with you'}</h3><p>{selected.check[locale]}</p><p className="fine-print">{es?'Selección orientativa por tarea. Capacidad, disponibilidad y configuración requieren evaluación del sitio.':'Task-based starting points. Capacity, availability and configuration require a site assessment.'}</p></div><a className="btn-primary" href={waLink(message)} target="_blank" rel="noopener noreferrer">{es?'Enviar mi proyecto por WhatsApp':'Send my project via WhatsApp'}<ArrowUpRight size={18}/></a><Link className="text-link" href={localPath('/reservar',locale)}>{es?'Prefiero reservar una llamada':'I prefer to book a call'}<ArrowUpRight size={16}/></Link><p className="fine-print">{es?'Estos datos permanecen en tu navegador hasta que eliges abrir WhatsApp y enviar el mensaje.':'This information stays in your browser until you choose to open WhatsApp and send the message.'}</p></div></section>;
}
