'use client';
import {useState} from 'react';
import {ArrowUpRight} from 'lucide-react';
import {waLink} from '@/lib/site';
import type {Locale} from '@/lib/locale';
export default function SupportRequest({locale='es'}:{locale?:Locale}){
 const es=locale==='es';const [model,setModel]=useState('');const [serial,setSerial]=useState('');const [city,setCity]=useState('');const [issue,setIssue]=useState('');
 const [kind,setKind]=useState('diagnosis');const kinds=[['diagnosis',es?'Diagnóstico':'Diagnosis'],['parts',es?'Refacción o consumible':'Part or consumable'],['maintenance',es?'Mantenimiento':'Maintenance'],['training',es?'Capacitación':'Training']];
 const message=(es?'Hola Botmate, necesito soporte.':'Hello Botmate, I need support.')+`\n${es?'Solicitud':'Request'}: ${kinds.find(k=>k[0]===kind)![1]}\n${es?'Modelo':'Model'}: ${model.trim()||'—'}\n${es?'Serie':'Serial'}: ${serial.trim()||'—'}\n${es?'Ciudad':'City'}: ${city.trim()||'—'}\n${es?'Detalle':'Details'}: ${issue.trim()||'—'}`;
 return <div className="support-request"><h2>{es?'Prepara tu solicitud.':'Prepare your request.'}</h2><p>{es?'Estos datos ayudan al equipo a orientar el diagnóstico y revisar compatibilidad.':'These details help the team assess the issue and check compatibility.'}</p><div className="support-fields"><label>{es?'Tipo de atención':'Request type'}<select value={kind} onChange={e=>setKind(e.target.value)}>{kinds.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>{es?'Modelo del equipo':'Robot model'}<input value={model} onChange={e=>setModel(e.target.value)} maxLength={80} placeholder="PUDU CC1, T300…"/></label><label>{es?'Número de serie (si lo tienes)':'Serial number (if available)'}<input value={serial} onChange={e=>setSerial(e.target.value)} maxLength={80}/></label><label>{es?'Ciudad':'City'}<input value={city} onChange={e=>setCity(e.target.value)} maxLength={80}/></label><label className="support-full">{es?'¿Qué ocurre o qué necesitas?':'What is happening or what do you need?'}<textarea value={issue} onChange={e=>setIssue(e.target.value)} maxLength={1200} rows={4}/></label></div><a className="btn-primary" href={waLink(message)} target="_blank" rel="noopener noreferrer">{es?'Abrir solicitud en WhatsApp':'Open request in WhatsApp'}<ArrowUpRight size={18}/></a><p className="fine-print">{es?'Puedes adjuntar fotos en WhatsApp. Tú decides cuándo enviar el mensaje. Este formulario no crea un ticket ni confirma una visita; el equipo acuerda contigo los siguientes pasos.':'You can attach photos in WhatsApp. You decide when to send the message. This form does not create a ticket or confirm a visit; the team agrees next steps with you.'}</p></div>;
}
