export const legacyEnglishPosts = [
 {slug:'botmate-serve-vs-botmate-ads-cual-elegir',title:'Delivery or advertising: define your robot’s priority',excerpt:'Choose according to the task, route and content your business needs.',sections:[{title:'Start with the task',text:'Record what is transported, how often the route repeats and who loads and unloads. If communication is your priority, define the content, audience and interaction point before choosing a screen.'},{title:'Compare the working space',text:'Measure aisles with furniture in its usual position. Consider pedestrian crossings and waiting areas. Identify floor types, level changes and charging locations.'},{title:'Request a relevant demonstration',text:'The demonstration should represent the task you need to address. Observe the complete route, interaction with your team and what happens when the robot encounters an obstacle. An advertising accessory or tray can change the required configuration.'}]},
 {slug:'roi-renta-de-robots-restaurantes',title:'How to assess the cost of introducing a robot',excerpt:'Organize operating costs and measurements before comparing rental and purchase.',sections:[{title:'Define what you want to measure',text:'Choose a specific task and record how it is performed today: frequency, journey duration and people involved. Avoid attributing to robotics changes that may also result from schedules, staffing or demand.'},{title:'Compare the full cost',text:'Include the selected equipment and accessories, transport, installation, integrations, training, maintenance and consumables. Account for the team’s preparation and follow-up time.'},{title:'Repeat measurements under comparable conditions',text:'Evaluate the same route and a similar workload during the trial. Document completed tasks and staff interventions. This record helps you decide whether the solution makes sense for your project; it does not replace a quotation or guarantee savings.'}]},
 {slug:'como-implementar-robot-en-restaurante',title:'Prepare your restaurant for a demonstration',excerpt:'What to review before trying a service robot in your space.',sections:[{title:'Draw the usual route',text:'Mark the starting point, destinations and waiting areas. Include doors, furniture and points where customers and staff cross paths. Measure the narrowest passages to compare with the model’s specifications.'},{title:'Organize the people involved',text:'Define who loads, unloads and requests a route. Prepare a representative service task. Agree how blocked routes and pauses will be handled, and assign someone to record observations.'},{title:'Observe more than the arrival',text:'Review load stability, crossings, waiting times and ease of use for staff. Afterwards, identify conditions that need adjustment and request a proposal explaining commissioning and training scope.'}]},
 {slug:'limpieza-autonoma-botmate-clean-vs-tradicional',title:'Autonomous and operator-guided cleaning: different tasks',excerpt:'Prepare a cleaning-equipment assessment without confusing how the products are operated.',sections:[{title:'Classify your surfaces',text:'Record floor types, area and scheduling restrictions. Consider obstacles, delicate materials, carpets and areas that require your organization’s specific protocols.'},{title:'Distinguish how the equipment is operated',text:'An autonomous solution needs defined routes and working conditions. An operator-guided scrubber depends on a person’s direction. Check how the exact model is used before planning shifts or reassigning tasks.'},{title:'Review consumables and service',text:'Check brush, filter and cleaning-product compatibility. Review access to charging, water and waste disposal, detail work that remains with staff, and maintenance and training included in the proposal.'}]},
 {slug:'futuro-robotica-mexico-2026',title:'What to ask before choosing a robotics supplier',excerpt:'A practical guide to comparing proposals by scope and clarity.',sections:[{title:'Identify the exact equipment',text:'Request the manufacturer, full model name, version and accessories. A photograph or commercial name alone does not define the configuration you will receive.'},{title:'Put the conditions in writing',text:'Confirm pricing and included items, availability, delivery, site requirements, warranty, maintenance and support channels. Define supplier and customer responsibilities.'},{title:'Request evidence related to your task',text:'If a proposal includes savings or productivity percentages, ask how they were measured, under what conditions and over what period. Another operation’s experience can inform the conversation but does not replace assessment of your own space.'}]},
];
export const legacyEnglishRobots = [
 {slug:'botmate-glide',name:'SwiftBot',description:'A delivery robot for hospitality spaces.',text:'Support delivery routes within restaurants and other service spaces. Suitability depends on the layout and conditions of the site.',image:'/photos/robots/botmate-glide.jpg'},
 {slug:'botmate-tower',name:'FlashBot',description:'Delivery between areas of a building.',text:'A building-delivery robot. Elevator use requires a compatibility and integration assessment. Confirm the generation and exact version; FlashBot Max is a separate current model.',image:'/photos/robots/botmate-tower.jpg'},
 {slug:'botmate-carry',name:'Pudu HolaBot',description:'Support for dish collection and transport.',text:'A delivery robot with calling and notification functions for transport tasks. Staff remain responsible for loading and unloading.',image:''},
];
