// Vitala — banco de recetas del mundo (accesibles, saludables, con preparación).
// Cocinas: México, Mediterráneo, Japón, India, Perú, Grecia, Medio Oriente, Tailandia…
// Cada receta trae etiquetado de alérgenos, compatibilidad con preferencias y
// pasos de preparación claros. Valores nutricionales aproximados por porción base.

import type { Allergen, MealSlot } from "./types";

export interface Meal {
  id: string;
  slot: MealSlot;
  name: string;
  origin: string; // cocina de origen
  items: string[];
  steps: string[]; // preparación paso a paso
  baseKcal: number;
  protein: number;
  carbs: number;
  fat: number;
  prepMin: number;
  allergens: Allergen[];
  landMeat: boolean; // carne terrestre (res, pollo, cerdo)
  vegetarian: boolean;
  vegan: boolean;
  keto: boolean;
  mediterranean: boolean;
}

export const MEALS: Meal[] = [
  // ───────────── DESAYUNO ─────────────
  {
    id: "d1",
    slot: "desayuno",
    name: "Avena cremosa con plátano y crema de cacahuate",
    origin: "Global",
    items: ["60 g avena", "1 plátano", "1 cda crema de cacahuate", "Canela", "250 ml agua o leche vegetal"],
    steps: [
      "Hierve la avena con el líquido a fuego medio 5 minutos, moviendo de vez en cuando.",
      "Rebana el plátano y añade la mitad a la olla para que se integre.",
      "Sirve y corona con el resto del plátano, la crema de cacahuate y canela.",
    ],
    baseKcal: 420, protein: 14, carbs: 62, fat: 13, prepMin: 8,
    allergens: ["gluten", "cacahuate"], landMeat: false,
    vegetarian: true, vegan: true, keto: false, mediterranean: true,
  },
  {
    id: "d2",
    slot: "desayuno",
    name: "Huevos revueltos con espinaca y aguacate",
    origin: "México",
    items: ["3 huevos", "1 taza espinaca", "1/2 aguacate", "Jitomate"],
    steps: [
      "Saltea la espinaca y el jitomate picado 2 minutos en un sartén con poco aceite.",
      "Bate los huevos y viértelos; revuelve a fuego bajo hasta que cuajen suaves.",
      "Sirve con el aguacate en láminas y una pizca de sal y pimienta.",
    ],
    baseKcal: 380, protein: 22, carbs: 9, fat: 28, prepMin: 10,
    allergens: ["huevo"], landMeat: false,
    vegetarian: true, vegan: false, keto: true, mediterranean: true,
  },
  {
    id: "d3",
    slot: "desayuno",
    name: "Yogur griego con fresas, nuez y miel",
    origin: "Grecia",
    items: ["200 g yogur griego natural", "1 taza fresas", "20 g nuez", "1 cdita miel"],
    steps: [
      "Sirve el yogur en un tazón frío.",
      "Lava y parte las fresas; acomódalas encima con la nuez troceada.",
      "Termina con un hilo fino de miel.",
    ],
    baseKcal: 330, protein: 20, carbs: 30, fat: 14, prepMin: 5,
    allergens: ["lacteos", "frutos_secos"], landMeat: false,
    vegetarian: true, vegan: false, keto: false, mediterranean: true,
  },
  {
    id: "d4",
    slot: "desayuno",
    name: "Tofu revuelto a la mexicana",
    origin: "México",
    items: ["200 g tofu firme", "Jitomate", "Cebolla", "Chile", "Tortilla de maíz"],
    steps: [
      "Desmorona el tofu con un tenedor y escúrrelo bien.",
      "Sofríe cebolla, jitomate y chile picados 3 minutos.",
      "Añade el tofu con sal y una pizca de cúrcuma; cocina 5 minutos.",
      "Sirve con tortillas de maíz calientes.",
    ],
    baseKcal: 350, protein: 20, carbs: 30, fat: 16, prepMin: 12,
    allergens: ["soya"], landMeat: false,
    vegetarian: true, vegan: true, keto: false, mediterranean: false,
  },
  {
    id: "d5",
    slot: "desayuno",
    name: "Smoothie verde con proteína de chícharo",
    origin: "Global",
    items: ["1 scoop proteína de chícharo", "Espinaca", "1 manzana", "Linaza", "Agua"],
    steps: [
      "Trocea la manzana y ponla en la licuadora con la espinaca lavada.",
      "Agrega la proteína, la linaza y agua fría al gusto.",
      "Licúa 60 segundos hasta que quede terso y sirve de inmediato.",
    ],
    baseKcal: 300, protein: 25, carbs: 32, fat: 7, prepMin: 5,
    allergens: [], landMeat: false,
    vegetarian: true, vegan: true, keto: false, mediterranean: false,
  },
  {
    id: "d6",
    slot: "desayuno",
    name: "Chilaquiles verdes horneados con frijoles",
    origin: "México",
    items: ["Tortilla horneada", "Salsa verde", "1/2 taza frijoles", "Queso fresco"],
    steps: [
      "Corta las tortillas en triángulos y h.ornéalas 8 minutos hasta que doren (sin freír).",
      "Calienta la salsa verde y baña los totopos justo antes de servir.",
      "Acompaña con frijoles calientes y espolvorea queso fresco.",
    ],
    baseKcal: 410, protein: 16, carbs: 52, fat: 15, prepMin: 15,
    allergens: ["lacteos"], landMeat: false,
    vegetarian: true, vegan: false, keto: false, mediterranean: false,
  },
  {
    id: "d7",
    slot: "desayuno",
    name: "Shakshuka — huevos pochados en salsa de jitomate",
    origin: "Medio Oriente",
    items: ["2 huevos", "2 jitomates", "1/2 cebolla", "Pimiento", "Pimentón y comino", "Pan integral"],
    steps: [
      "Sofríe cebolla y pimiento 4 minutos; añade jitomate picado, pimentón y comino.",
      "Cocina la salsa 8 minutos hasta que espese.",
      "Haz dos huecos y casca los huevos dentro; tapa y cocina 5 minutos.",
      "Sirve en el mismo sartén con pan integral para acompañar.",
    ],
    baseKcal: 360, protein: 18, carbs: 34, fat: 17, prepMin: 20,
    allergens: ["huevo", "gluten"], landMeat: false,
    vegetarian: true, vegan: false, keto: false, mediterranean: true,
  },
  {
    id: "d8",
    slot: "desayuno",
    name: "Toast de aguacate con huevo pochado",
    origin: "Australia",
    items: ["2 reb. pan integral", "1 aguacate", "1 huevo", "Limón", "Hojuelas de chile"],
    steps: [
      "Tuesta el pan y machaca el aguacate con limón y sal.",
      "Pocha el huevo 3 minutos en agua con un chorrito de vinagre.",
      "Unta el aguacate, corona con el huevo y termina con hojuelas de chile.",
    ],
    baseKcal: 390, protein: 15, carbs: 34, fat: 22, prepMin: 10,
    allergens: ["gluten", "huevo"], landMeat: false,
    vegetarian: true, vegan: false, keto: false, mediterranean: true,
  },

  // ───────────── COMIDA ─────────────
  {
    id: "c1",
    slot: "comida",
    name: "Pechuga de pollo con arroz integral y verduras",
    origin: "Global",
    items: ["150 g pollo", "1 taza arroz integral", "Brócoli", "Zanahoria"],
    steps: [
      "Cuece el arroz integral (2 partes de agua por 1 de arroz, ~25 min).",
      "Sazona el pollo con sal, pimienta y limón; c.ocínalo a la plancha 5-6 min por lado.",
      "Cuece el brócoli y la zanahoria al vapor 6 minutos.",
      "Sirve todo junto con un chorrito de aceite de oliva.",
    ],
    baseKcal: 520, protein: 42, carbs: 55, fat: 12, prepMin: 25,
    allergens: [], landMeat: true,
    vegetarian: false, vegan: false, keto: false, mediterranean: true,
  },
  {
    id: "c2",
    slot: "comida",
    name: "Salmón al horno con quinoa y espárragos",
    origin: "Mediterráneo",
    items: ["150 g salmón", "3/4 taza quinoa", "Espárragos", "Limón"],
    steps: [
      "Enjuaga la quinoa y cuécela 15 minutos en agua con sal.",
      "Hornea el salmón con limón, sal y aceite de oliva a 200°C por 12-14 minutos.",
      "Asa los espárragos en el mismo horno los últimos 8 minutos.",
    ],
    baseKcal: 540, protein: 38, carbs: 42, fat: 22, prepMin: 25,
    allergens: ["pescado"], landMeat: false,
    vegetarian: false, vegan: false, keto: false, mediterranean: true,
  },
  {
    id: "c3",
    slot: "comida",
    name: "Bowl de lentejas, arroz y verduras asadas",
    origin: "Mediterráneo",
    items: ["1 taza lentejas", "1/2 taza arroz", "Pimiento", "Calabacita", "Aceite de oliva"],
    steps: [
      "Cuece las lentejas 20 minutos y el arroz aparte.",
      "Asa pimiento y calabacita en trozos con aceite de oliva y sal a 220°C por 15 min.",
      "Arma el bowl: arroz, lentejas y verduras; termina con aceite de oliva crudo.",
    ],
    baseKcal: 500, protein: 24, carbs: 78, fat: 10, prepMin: 30,
    allergens: [], landMeat: false,
    vegetarian: true, vegan: true, keto: false, mediterranean: true,
  },
  {
    id: "c4",
    slot: "comida",
    name: "Tacos de res magra con nopales",
    origin: "México",
    items: ["150 g res magra", "Nopales", "3 tortillas de maíz", "Pico de gallo"],
    steps: [
      "Asa los nopales en tiras hasta que cambien de color.",
      "Sella la res en sartén caliente 3-4 minutos; pícala fina.",
      "Calienta las tortillas y arma los tacos con res, nopales y pico de gallo.",
    ],
    baseKcal: 510, protein: 40, carbs: 48, fat: 16, prepMin: 25,
    allergens: [], landMeat: true,
    vegetarian: false, vegan: false, keto: false, mediterranean: false,
  },
  {
    id: "c5",
    slot: "comida",
    name: "Ensalada mediterránea con garbanzo y atún",
    origin: "Mediterráneo",
    items: ["1 lata atún", "1/2 taza garbanzo", "Pepino", "Jitomate", "Aceitunas", "Aceite de oliva"],
    steps: [
      "Pica pepino y jitomate en cubos; mezcla con el garbanzo cocido y las aceitunas.",
      "Incorpora el atún escurrido.",
      "Aliña con aceite de oliva, limón, sal y orégano.",
    ],
    baseKcal: 470, protein: 36, carbs: 32, fat: 22, prepMin: 12,
    allergens: ["pescado"], landMeat: false,
    vegetarian: false, vegan: false, keto: false, mediterranean: true,
  },
  {
    id: "c6",
    slot: "comida",
    name: "Curry tailandés de tofu y verduras con coco",
    origin: "Tailandia",
    items: ["200 g tofu", "Leche de coco", "Brócoli", "Pimiento", "1/2 taza arroz"],
    steps: [
      "Dora el tofu en cubos hasta que quede crujiente por fuera.",
      "Sofríe el pimiento, añade pasta o polvo de curry y la leche de coco.",
      "Agrega brócoli y tofu; cocina 8 minutos a fuego suave.",
      "Sirve sobre arroz al vapor.",
    ],
    baseKcal: 530, protein: 26, carbs: 50, fat: 25, prepMin: 28,
    allergens: ["soya"], landMeat: false,
    vegetarian: true, vegan: true, keto: false, mediterranean: false,
  },
  {
    id: "c7",
    slot: "comida",
    name: "Salmón teriyaki con arroz y brócoli",
    origin: "Japón",
    items: ["150 g salmón", "2 cdas salsa de soya baja en sodio", "1 cdita miel", "Jengibre", "1 taza arroz", "Brócoli"],
    steps: [
      "Mezcla soya, miel y jengibre rallado para el glaseado teriyaki.",
      "Sella el salmón 3 minutos por lado; baña con el glaseado y reduce 2 minutos.",
      "Sirve sobre arroz al vapor con brócoli cocido.",
    ],
    baseKcal: 550, protein: 38, carbs: 52, fat: 20, prepMin: 20,
    allergens: ["pescado", "soya"], landMeat: false,
    vegetarian: false, vegan: false, keto: false, mediterranean: false,
  },
  {
    id: "c8",
    slot: "comida",
    name: "Dal de lentejas rojas con arroz basmati",
    origin: "India",
    items: ["1 taza lentejas rojas", "Cúrcuma, comino y jengibre", "Jitomate", "1/2 taza arroz basmati", "Cilantro"],
    steps: [
      "Sofríe jitomate con cúrcuma, comino y jengibre 3 minutos.",
      "Añade las lentejas y 3 tazas de agua; cocina 20 minutos hasta que se deshagan.",
      "Ajusta sal, sirve sobre arroz basmati y corona con cilantro fresco.",
    ],
    baseKcal: 490, protein: 24, carbs: 80, fat: 8, prepMin: 30,
    allergens: [], landMeat: false,
    vegetarian: true, vegan: true, keto: false, mediterranean: false,
  },
  {
    id: "c9",
    slot: "comida",
    name: "Poke bowl de atún con arroz y edamame",
    origin: "Hawai",
    items: ["120 g atún fresco", "1 taza arroz", "Edamame", "Pepino", "Aguacate", "Soya y ajonjolí"],
    steps: [
      "Corta el atún en cubos y marínalo 10 minutos con soya y ajonjolí.",
      "Arma el bowl: arroz tibio, edamame, pepino y aguacate.",
      "Corona con el atún marinado y sirve frío.",
    ],
    baseKcal: 540, protein: 35, carbs: 58, fat: 18, prepMin: 18,
    allergens: ["pescado", "soya", "ajonjoli"], landMeat: false,
    vegetarian: false, vegan: false, keto: false, mediterranean: false,
  },
  {
    id: "c10",
    slot: "comida",
    name: "Ceviche de pescado blanco con camote",
    origin: "Perú",
    items: ["180 g pescado blanco fresco", "6 limones", "Cebolla morada", "Cilantro", "Camote cocido", "Maíz"],
    steps: [
      "Corta el pescado en cubos y cúbrelo con jugo de limón y sal 15 minutos en refrigeración.",
      "Añade cebolla morada en pluma y cilantro picado.",
      "Sirve frío acompañado de camote cocido y maíz.",
    ],
    baseKcal: 460, protein: 36, carbs: 56, fat: 8, prepMin: 25,
    allergens: ["pescado"], landMeat: false,
    vegetarian: false, vegan: false, keto: false, mediterranean: false,
  },

  // ───────────── CENA ─────────────
  {
    id: "n1",
    slot: "cena",
    name: "Omelette de claras con champiñones y queso",
    origin: "Francia",
    items: ["4 claras + 1 huevo", "Champiñones", "30 g queso panela", "Espinaca"],
    steps: [
      "Saltea champiñones y espinaca 3 minutos.",
      "Bate claras y huevo; vierte en sartén antiadherente a fuego bajo.",
      "Añade el relleno y el queso, dobla el omelette y sirve.",
    ],
    baseKcal: 300, protein: 30, carbs: 8, fat: 16, prepMin: 12,
    allergens: ["huevo", "lacteos"], landMeat: false,
    vegetarian: true, vegan: false, keto: true, mediterranean: true,
  },
  {
    id: "n2",
    slot: "cena",
    name: "Pescado blanco a la plancha con ensalada",
    origin: "Mediterráneo",
    items: ["150 g pescado blanco", "Mezcla de hojas verdes", "Aguacate", "Limón"],
    steps: [
      "Sazona el pescado con sal, pimienta y limón.",
      "C.ocínalo a la plancha 3-4 minutos por lado.",
      "Sirve sobre hojas verdes con aguacate y un hilo de aceite de oliva.",
    ],
    baseKcal: 340, protein: 34, carbs: 12, fat: 18, prepMin: 18,
    allergens: ["pescado"], landMeat: false,
    vegetarian: false, vegan: false, keto: true, mediterranean: true,
  },
  {
    id: "n3",
    slot: "cena",
    name: "Crema de calabaza con semillas y pan integral",
    origin: "Global",
    items: ["Calabaza", "Caldo de verduras", "Semillas de calabaza", "1 reb. pan integral"],
    steps: [
      "Cuece la calabaza en el caldo 15 minutos hasta que esté suave.",
      "Licúa hasta obtener una crema tersa; ajusta sal y pimienta.",
      "Sirve con semillas tostadas encima y pan integral.",
    ],
    baseKcal: 320, protein: 12, carbs: 44, fat: 11, prepMin: 20,
    allergens: ["gluten"], landMeat: false,
    vegetarian: true, vegan: true, keto: false, mediterranean: true,
  },
  {
    id: "n4",
    slot: "cena",
    name: "Wrap integral de pollo y verduras",
    origin: "Global",
    items: ["120 g pollo", "Tortilla integral", "Lechuga", "Jitomate", "Yogur natural"],
    steps: [
      "Cocina el pollo en tiras con sal y pimentón.",
      "Calienta la tortilla y úntala con yogur natural.",
      "Rellena con pollo, lechuga y jitomate; enrolla firme y corta a la mitad.",
    ],
    baseKcal: 380, protein: 34, carbs: 36, fat: 11, prepMin: 15,
    allergens: ["gluten", "lacteos"], landMeat: true,
    vegetarian: false, vegan: false, keto: false, mediterranean: false,
  },
  {
    id: "n5",
    slot: "cena",
    name: "Ensalada de garbanzo, espinaca y aguacate",
    origin: "Mediterráneo",
    items: ["1 taza garbanzo", "Espinaca", "1/2 aguacate", "Aceite de oliva", "Limón"],
    steps: [
      "Mezcla el garbanzo cocido con la espinaca lavada.",
      "Añade el aguacate en cubos.",
      "Aliña con aceite de oliva, limón, sal y pimienta.",
    ],
    baseKcal: 360, protein: 16, carbs: 38, fat: 17, prepMin: 10,
    allergens: [], landMeat: false,
    vegetarian: true, vegan: true, keto: false, mediterranean: true,
  },
  {
    id: "n6",
    slot: "cena",
    name: "Sopa de verduras con frijol y queso fresco",
    origin: "México",
    items: ["Verduras mixtas", "1/2 taza frijol", "30 g queso fresco", "Cilantro"],
    steps: [
      "Cuece las verduras en caldo 12 minutos.",
      "Añade el frijol cocido y deja hervir 5 minutos más.",
      "Sirve con queso fresco desmoronado y cilantro.",
    ],
    baseKcal: 330, protein: 18, carbs: 42, fat: 9, prepMin: 22,
    allergens: ["lacteos"], landMeat: false,
    vegetarian: true, vegan: false, keto: false, mediterranean: false,
  },
  {
    id: "n7",
    slot: "cena",
    name: "Sopa miso con tofu, alga y cebollín",
    origin: "Japón",
    items: ["2 cdas pasta miso", "150 g tofu suave", "Alga wakame", "Cebollín", "1/2 taza arroz opcional"],
    steps: [
      "Hidrata el alga wakame 5 minutos en agua fría.",
      "Calienta 500 ml de agua sin que hierva y disuelve la pasta miso.",
      "Añade el tofu en cubos y el alga; calienta 2 minutos sin hervir.",
      "Sirve con cebollín fresco.",
    ],
    baseKcal: 280, protein: 18, carbs: 26, fat: 10, prepMin: 12,
    allergens: ["soya"], landMeat: false,
    vegetarian: true, vegan: true, keto: false, mediterranean: false,
  },
  {
    id: "n8",
    slot: "cena",
    name: "Ensalada griega con queso feta y aceitunas",
    origin: "Grecia",
    items: ["Jitomate", "Pepino", "Cebolla morada", "40 g queso feta", "Aceitunas kalamata", "Orégano y aceite de oliva"],
    steps: [
      "Corta jitomate, pepino y cebolla en trozos grandes.",
      "Añade las aceitunas y el queso feta en cubos.",
      "Aliña con aceite de oliva, orégano y una pizca de sal.",
    ],
    baseKcal: 320, protein: 11, carbs: 18, fat: 24, prepMin: 10,
    allergens: ["lacteos"], landMeat: false,
    vegetarian: true, vegan: false, keto: true, mediterranean: true,
  },

  // ───────────── SNACK ─────────────
  {
    id: "s1",
    slot: "snack",
    name: "Manzana con almendras",
    origin: "Global",
    items: ["1 manzana", "20 g almendras"],
    steps: ["Lava la manzana y córtala en gajos.", "Acompáñala con las almendras."],
    baseKcal: 200, protein: 5, carbs: 26, fat: 11, prepMin: 1,
    allergens: ["frutos_secos"], landMeat: false,
    vegetarian: true, vegan: true, keto: false, mediterranean: true,
  },
  {
    id: "s2",
    slot: "snack",
    name: "Yogur griego con arándanos",
    origin: "Grecia",
    items: ["150 g yogur griego", "1/2 taza arándanos"],
    steps: ["Sirve el yogur frío.", "Corona con los arándanos lavados."],
    baseKcal: 180, protein: 16, carbs: 20, fat: 4, prepMin: 2,
    allergens: ["lacteos"], landMeat: false,
    vegetarian: true, vegan: false, keto: false, mediterranean: true,
  },
  {
    id: "s3",
    slot: "snack",
    name: "Hummus con bastones de zanahoria y pepino",
    origin: "Medio Oriente",
    items: ["4 cda hummus", "Zanahoria", "Pepino"],
    steps: ["Corta zanahoria y pepino en bastones.", "Sirve con el hummus para dipear."],
    baseKcal: 190, protein: 7, carbs: 22, fat: 9, prepMin: 5,
    allergens: ["ajonjoli"], landMeat: false,
    vegetarian: true, vegan: true, keto: false, mediterranean: true,
  },
  {
    id: "s4",
    slot: "snack",
    name: "Edamames al vapor con sal de mar",
    origin: "Japón",
    items: ["1 taza edamames", "Sal de mar"],
    steps: ["Cuece los edamames al vapor 5 minutos.", "Espolvorea sal de mar y sirve tibios."],
    baseKcal: 190, protein: 17, carbs: 15, fat: 8, prepMin: 6,
    allergens: ["soya"], landMeat: false,
    vegetarian: true, vegan: true, keto: false, mediterranean: false,
  },
  {
    id: "s5",
    slot: "snack",
    name: "Puño de nueces y chocolate amargo 85%",
    origin: "Global",
    items: ["25 g nueces mixtas", "10 g chocolate 85%"],
    steps: ["Sirve las nueces con el cuadrito de chocolate.", "Disfruta despacio, sin pantalla de por medio."],
    baseKcal: 210, protein: 5, carbs: 12, fat: 17, prepMin: 1,
    allergens: ["frutos_secos"], landMeat: false,
    vegetarian: true, vegan: true, keto: true, mediterranean: true,
  },
  {
    id: "s6",
    slot: "snack",
    name: "Jícama con limón y chile",
    origin: "México",
    items: ["1 taza jícama", "Limón", "Chile en polvo"],
    steps: ["Pela y corta la jícama en bastones.", "Baña con limón y espolvorea chile al gusto."],
    baseKcal: 90, protein: 2, carbs: 20, fat: 0, prepMin: 3,
    allergens: [], landMeat: false,
    vegetarian: true, vegan: true, keto: false, mediterranean: false,
  },
  {
    id: "s7",
    slot: "snack",
    name: "Pan pita con tzatziki",
    origin: "Grecia",
    items: ["1/2 pan pita integral", "4 cdas yogur griego", "Pepino rallado", "Ajo y eneldo"],
    steps: [
      "Mezcla el yogur con pepino rallado y escurrido, ajo picado y eneldo.",
      "Tuesta ligeramente el pan pita y córtalo en triángulos.",
      "Sirve el tzatziki frío para dipear.",
    ],
    baseKcal: 180, protein: 9, carbs: 24, fat: 5, prepMin: 7,
    allergens: ["gluten", "lacteos"], landMeat: false,
    vegetarian: true, vegan: false, keto: false, mediterranean: true,
  },
];
