import type {Localized} from './locale';
export const solutionTasks:{id:string;label:Localized;description:Localized;category:string;models?:string[];check:Localized}[]=[
 {id:'cleaning',label:{es:'Limpiar pisos',en:'Clean floors'},description:{es:'Limpieza comercial e industrial',en:'Commercial and industrial cleaning'},category:'cleaning',check:{es:'Medimos superficie, tipo de suciedad, piso, obstáculos y tiempos disponibles. SH1 requiere operador.',en:'We assess area, debris, flooring, obstacles and available time. SH1 requires an operator.'}},
 {id:'delivery',label:{es:'Servir y entregar',en:'Serve and deliver'},description:{es:'Restaurantes, hoteles y atención',en:'Restaurants, hotels and service'},category:'delivery',check:{es:'Revisamos bandejas, tamaño de carga, ancho de paso y puntos de entrega; puertas y elevadores requieren compatibilidad.',en:'We review trays, load dimensions, aisle width and delivery points; doors and elevators require compatibility checks.'}},
 {id:'industrial',label:{es:'Mover materiales',en:'Move materials'},description:{es:'Fábricas, plantas y almacenes',en:'Factories, plants and warehouses'},category:'industrial',check:{es:'Validamos peso y centro de gravedad, interfaces de carga, tráfico, pendientes y convivencia con personas.',en:'We validate payload and center of gravity, loading interfaces, traffic, slopes and interaction with people.'}},
 {id:'advertising',label:{es:'Activar una marca',en:'Activate a brand'},description:{es:'Eventos, pantallas y promoción',en:'Events, screens and promotion'},category:'delivery',models:['kettybot-pro','bellabot-pro','pudubot-2'],check:{es:'Definimos contenido, personalización, formato de pantalla y recorrido. Las pantallas y adaptaciones adicionales se cotizan por separado.',en:'We define content, branding, screen format and routes. Additional screens and adaptations are quoted separately.'}},
 {id:'outdoor',label:{es:'Cuidar áreas verdes',en:'Maintain green spaces'},description:{es:'Jardines y mantenimiento de césped',en:'Gardens and turf maintenance'},category:'outdoor',check:{es:'Evaluamos extensión, pendientes, límites, obstáculos y condiciones del césped antes de definir la solución.',en:'We assess area, slopes, boundaries, obstacles and turf conditions before defining the solution.'}},
 {id:'ai',label:{es:'Explorar robótica e IA',en:'Explore robotics and AI'},description:{es:'Nuevas aplicaciones y capacidades',en:'Emerging applications and capabilities'},category:'ai',check:{es:'Distinguimos demostraciones tecnológicas de funciones comerciales disponibles. El alcance se valida con Botmate.',en:'We distinguish technology demonstrations from available commercial features. Botmate validates the scope.'}},
];
