import type {Localized} from './locale';
export const supportFaqs:{q:Localized;a:Localized}[]=[
 {q:{es:'¿Cómo elijo un robot para mi empresa en México?',en:'How do I choose a robot for my business in Mexico?'},a:{es:'Empieza por una tarea: limpiar, entregar, mover materiales, comunicar o cuidar el césped. Después revisa dimensiones, peso, recorridos, pisos y horarios con Botmate. El selector ayuda a explorar modelos; la recomendación final requiere evaluar tu operación.',en:'Start with a task: cleaning, delivery, material handling, communication or turf care. Then review dimensions, payloads, routes, floors and schedules with Botmate. The finder helps you explore models; the final recommendation requires assessing your operation.'}},
 {q:{es:'¿Puedo rentar o comprar un robot?',en:'Can I rent or buy a robot?'},a:{es:'Puedes consultar ambas modalidades. Modelo, plazo, disponibilidad, transporte, instalación y servicio se confirman en una cotización personalizada. El catálogo global no implica inventario inmediato en México.',en:'You can enquire about either option. Model, term, availability, transport, installation and service are confirmed in a personalized quote. The global catalog does not imply immediate stock in Mexico.'}},
 {q:{es:'¿Cuánto cuesta un robot o una renta?',en:'How much does a robot or rental cost?'},a:{es:'El precio depende del equipo, la configuración, la duración y el alcance operativo. Comparte ciudad, fecha, tarea y modalidad para preparar una propuesta que distinga equipo, accesorios y servicios.',en:'Pricing depends on the unit, configuration, duration and operational scope. Share your city, date, task and preferred option to prepare a proposal distinguishing the robot, accessories and services.'}},
 {q:{es:'¿Qué incluye la llamada del calendario?',en:'What does the calendar appointment include?'},a:{es:'El calendario permite reservar una conversación de 30 minutos por Google Meet. Una demostración presencial, disponibilidad del robot y traslado se coordinan después con el equipo; reservar la llamada no reserva un robot.',en:'The calendar lets you book a 30-minute Google Meet conversation. An on-site demonstration, robot availability and transport are coordinated separately with the team; booking a call does not reserve a robot.'}},
 {q:{es:'¿Atienden proyectos fuera de CDMX?',en:'Do you handle projects outside Mexico City?'},a:{es:'Recibimos consultas para proyectos en México. Indica ciudad, ubicación de la sede y fechas para confirmar cobertura, traslados y disponibilidad en la propuesta.',en:'We accept enquiries for projects in Mexico. Share the city, venue location and dates to confirm coverage, transport and availability in the proposal.'}},
 {q:{es:'¿Qué debo medir antes de una demostración?',en:'What should I measure before a demonstration?'},a:{es:'Registra el pasillo más estrecho, puertas, desniveles, tipo de piso, carga y puntos de origen y destino. Incluye horarios, tráfico de personas y un espacio de carga eléctrica. Para limpieza y jardinería también importa la superficie.',en:'Record the narrowest aisle, doors, level changes, floor type, payload and pickup and drop-off points. Include schedules, foot traffic and a charging area. Surface area also matters for cleaning and turf care.'}},
 {q:{es:'¿Pueden entrar a fábricas y almacenes?',en:'Can robots operate in factories and warehouses?'},a:{es:'El catálogo incluye robots para logística industrial. La compatibilidad depende de la carga, interfaces de entrega, pendientes, pasillos, tráfico y reglas del sitio. La evaluación debe involucrar al equipo de operaciones y seguridad de la planta.',en:'The catalog includes industrial logistics robots. Compatibility depends on payload, transfer interfaces, slopes, aisles, traffic and site rules. Assessment should involve the plant’s operations and safety teams.'}},
 {q:{es:'¿Todos los equipos de limpieza son autónomos?',en:'Are all cleaning units autonomous?'},a:{es:'No. Por ejemplo, PUDU SH1 es una fregadora guiada por una persona. Las fichas distinguen este tipo de equipo de los robots autónomos; revisa el modo de operación de cada modelo.',en:'No. For example, PUDU SH1 is an operator-guided scrubber-dryer. Product profiles distinguish this equipment from autonomous robots; check each model’s operating mode.'}},
 {q:{es:'¿Se pueden personalizar para eventos y marcas?',en:'Can robots be customized for events and brands?'},a:{es:'Puedes consultar personalización gráfica y contenido de pantalla según el equipo. Definimos formatos, materiales, aprobación de artes y compatibilidad de adaptaciones en la propuesta. Una pantalla adicional puede requerir configuración específica.',en:'You can enquire about graphic customization and screen content depending on the unit. Formats, materials, artwork approval and adaptation compatibility are defined in the proposal. An additional screen may require a specific configuration.'}},
 {q:{es:'¿Qué capacitación, garantía y mantenimiento incluyen?',en:'What training, warranty and maintenance are included?'},a:{es:'Su alcance depende del modelo y la propuesta. Pide que se especifiquen puesta en marcha, capacitación, responsables, mantenimiento, consumibles, cobertura de garantía y exclusiones. La ficha del catálogo no sustituye esas condiciones por escrito.',en:'Scope depends on the model and proposal. Ask for commissioning, training, responsibilities, maintenance, consumables, warranty coverage and exclusions to be specified. A catalog profile does not replace written terms.'}},
 {q:{es:'¿Cómo solicito soporte o una refacción?',en:'How do I request support or a spare part?'},a:{es:'Reúne modelo, número de serie, ciudad, descripción del problema y fotografías o código de error. Entra al centro de soporte para preparar el mensaje al equipo. Compatibilidad, diagnóstico, costo y existencia se confirman antes del servicio.',en:'Gather the model, serial number, city, problem description and photos or error code. Use the support center to prepare your message to the team. Compatibility, diagnosis, cost and stock are confirmed before service.'}},
 {q:{es:'¿Los resultados de otros clientes se replicarán en mi empresa?',en:'Will other customers’ results apply to my business?'},a:{es:'Cada operación tiene condiciones distintas. Una evaluación útil compara tareas, recorridos, intervenciones y tiempos antes y durante una prueba. Los casos internacionales de Pudu y los proyectos propios de Botmate se identifican por separado.',en:'Every operation has different conditions. A useful assessment compares tasks, routes, interventions and time before and during a trial. International Pudu cases and Botmate’s own projects are identified separately.'}},
];
