"""Botmate editorial adaptations. Facts are attributed to the linked manufacturer sources."""
import json,pathlib,hashlib,re
R=pathlib.Path(__file__).resolve().parents[1];d=json.loads((R/'lib/pudu-catalog.json').read_text());jobs=json.loads((R/'docs/pudu/web-media-jobs.json').read_text());home=json.loads((R/'.pudu-source/en.json').read_text())['data']['homePageData']
def b(es,en):return {'es':es,'en':en}
def img(url):
 p='/media/pudu/'+hashlib.sha256(url.encode()).hexdigest()[:16]+'.webp';jobs.append({'url':url,'path':p,'kind':'image'});return p
names=['KFC','Café de Coral','Pepsi','Walmart México y Centroamérica','Giovanni L.','Haidilao','Skylark Group','Sheraton','Din Tai Fung',"Dunkin’",'Bar-B-Q Plaza','Lao Xiang Ji',"M&M’s",'Tim Ho Wan','MediaMarkt','Panasonic','PappaRich','Pizza Hut','Black Canyon',"Johnny’s",'Carrefour','China Southern Airlines','Coca-Cola','Gami Chicken & Beer','Jollibee','MK Restaurants',"Maxim’s",'Marriott','Saizeriya','Shell']
for r,n in zip(d['logos'],names):r['name']=n
translations={
'pudu-t150':('Robot industrial para cargas ligeras',['Despliegue y mapeo','Navegación de precisión','Diseño de una pieza','Operación intuitiva']),
'pudu-mt1-max':('Barredora robótica con percepción 3D e IA',['Percepción tridimensional','Limpieza con IA','Interacción activa','Operación autónoma']),
'pudu-mt1-vac':('Barredora y aspiradora robótica con IA',['Aspiración de alta potencia','Limpieza de grandes superficies','Autonomía extendida','Limpieza adaptativa con IA']),
'flashbot-arm':('Robot de servicio semihumanoide con brazos',['Decisiones inteligentes','Operación autónoma','Brazos y manos articuladas','Interacción multimodal']),
'bellabot':('Robot de entrega para hospitalidad',['Interacción multimodal','Intercambio de batería','Detección de obstáculos','Entrega multifunción']),
}
for r in d['products']:
 if r['slug'] in translations:r['description']['es'],r['features']['es']=translations[r['slug']]
 # Short editorial wording instead of translating promotional absolutes.
 r['features']['es']=[x.replace('24/7','Continua').replace('24 horas del día, 7 días a la semana','continua') for x in r['features']['es']]
sceneTranslations={'About Material Delivery':'Traslado de materiales','About Cleaning':'Cuidado de pisos','Information Service':'Recepción e información','Floor Cleaning':'Limpieza de pisos','Promotion & Delivery':'Promoción y entrega'}
for r in d['industries']:
 for s in r['scenes']:s['title']['es']=sceneTranslations.get(s['title']['es'],s['title']['es']).replace('suelos','pisos')
partNames={'Retractable Tray Baffle':'Separador retráctil de bandeja','Protection Case':'Cubierta protectora','Display Stand':'Soporte de exhibición','Fixed Cup Holder':'Portavasos fijo','Rear Cover':'Cubierta posterior','Charging Station':'Estación de carga','Charging station':'Estación de carga','Conveyor-Single Layer':'Transportador de un nivel','Tray':'Bandeja','Towing Device':'Dispositivo de arrastre','Reflective Post':'Poste reflector','4G Watch':'Reloj 4G','Turnstiles/Automatic doors Control Components':'Módulo de control de puertas y accesos','PUDU Pager':'Botón de llamada PUDU','Telephone system':'Sistema telefónico','Flashbot vending machine':'Máquina dispensadora para FlashBot','PUDU Self-Cleaning Docking Station':'Estación de autolimpieza PUDU','PUDU Mobile Water Station':'Estación móvil de agua PUDU','Elevator Control Module':'Módulo de control de elevadores','Carpet Vacuuming Assembly':'Accesorio de aspiración de alfombras','Lifting Rack':'Rack de elevación','Auto-Empty Station':'Estación de vaciado automático'}
for p in d['accessories']:p['name']['es']=partNames.get(p['name']['en'],p['name']['es'])
# Short case adaptations, not promises about Botmate installations.
caseCopy=[
('food-bayana','Food Bayana','Malasia','Malaysia','hospitality',['flashbot-max'], 'Entregas en un centro gastronómico','Delivery in a dining complex','Food Bayana, en Penang, incorporó FlashBot en una colaboración con Pudu Robotics y Pentamaster. El caso explora la automatización de entregas dentro de un centro gastronómico.','Food Bayana in Penang introduced FlashBot through a collaboration with Pudu Robotics and Pentamaster. The case explores automated delivery within a dining complex.'),
('skylark','Skylark Group','Japón','Japan','food-and-beverage',['bellabot'],'Robots dentro del servicio de restaurante','Robots in restaurant service','Pudu documenta la incorporación de BellaBot en Skylark para apoyar el traslado de alimentos y reducir recorridos del personal. Su publicación describe un plan de 3,000 robots para más de 2,000 establecimientos.','Pudu documents BellaBot adoption at Skylark to assist food transport and reduce staff walking. Its case describes a plan for 3,000 robots across more than 2,000 locations.'),
('smile-park','Smile Park','Japón','Japan','health-care',['bellabot'],'Más tiempo para el cuidado de las personas','More time for resident care','La residencia Smile Park utiliza BellaBot para transportar artículos entre áreas. Según el caso de Pudu, el personal puede permanecer más tiempo en sus zonas de atención mientras el robot realiza recorridos de entrega.','Smile Park uses BellaBot to move items between areas. Pudu reports that staff can spend more time in their care areas while the robot handles delivery routes.'),
('manufactura-baterias','Manufactura de baterías','China','China','industrial-warehouse-logistics',['pudubot-2','pudu-cc1','pudu-t300'],'Tres robots, diferentes tareas','Three robots, different tasks','Un fabricante de baterías de ion-litio integra PuduBot 2, CC1 y T300 para combinar transporte y limpieza. Pudu no identifica públicamente al fabricante en este caso.','A lithium-ion battery manufacturer integrates PuduBot 2, CC1 and T300 to combine transport and cleaning. Pudu does not publicly identify the manufacturer in this case.'),
('mediamarkt','MediaMarkt','Países Bajos','Netherlands','retail',['kettybot-pro','bellabot'],'Orientación dentro de la tienda','In-store customer guidance','El caso de Pudu describe a KettyBot y BellaBot apoyando la orientación de clientes y la comunicación comercial. El personal configura información de productos y ubicaciones para guiar a los visitantes.','Pudu describes KettyBot and BellaBot assisting customer guidance and in-store communication. Staff configure product and location information to direct visitors.'),
('xtreme','Xtreme Trampoline Park','Canadá','Canada','entertainment-and-sports',['kettybot-pro','pudu-cc1'],'Servicio y limpieza en un espacio de juego','Service and cleaning in an entertainment venue','Xtreme combina KettyBot para entregas de alimentos durante fiestas con CC1 para el cuidado de pisos. El ejemplo muestra dos tareas complementarias dentro del mismo recinto.','Xtreme combines KettyBot food delivery during parties with CC1 floor care. The example shows two complementary tasks within the same venue.'),
('parkhotel','Parkhotel Eisenstadt','Austria','Austria','hospitality',['bellabot','flashbot-max','pudu-cc1'],'Una operación hotelera con varios robots','A hotel operation with multiple robots','Pudu presenta cinco modelos en Parkhotel: KettyBot, HolaBot, BellaBot, FlashBot y CC1. Las aplicaciones incluyen recepción, entrega de alimentos y artículos, y limpieza de pisos.','Pudu presents five models at Parkhotel: KettyBot, HolaBot, BellaBot, FlashBot and CC1. Applications include reception, food and item delivery, and floor cleaning.'),
('meritum','Meritum','Polonia','Poland','realestate-and-property-services',['kettybot-pro'],'Recepción y orientación en oficinas','Office reception and guidance','La firma de contabilidad y nómina Meritum incorporó KettyBot en recepción. El caso describe guía hacia salas y comunicación en pantalla para visitantes y colaboradores.','Accounting and payroll firm Meritum introduced KettyBot at reception. The case describes guidance to meeting rooms and on-screen communication for visitors and staff.'),
('mnactec','MNACTEC','España','Spain','public-service',['kettybot-pro'],'Tecnología que acompaña al visitante','Technology alongside museum visitors','El Museo Nacional de la Ciencia y la Técnica de Cataluña integró dos KettyBot en sus exposiciones. Pudu describe orientación e interacción mediante contenidos audiovisuales.','The National Museum of Science and Technology of Catalonia integrated two KettyBots into its exhibitions. Pudu describes navigation assistance and audiovisual interaction.'),
]
cases=[]
for h,c in zip(home['customers'],caseCopy):
 slug,brand,esCountry,enCountry,industry,models,esTitle,enTitle,esBody,enBody=c;source='https://www.pudurobotics.com/en'+re.sub('[\u200b\u200c\u200d\ufeff]','',h['jumpUrl']);cases.append({'slug':slug,'brand':brand,'country':b(esCountry,enCountry),'industry':industry,'models':models,'title':b(esTitle,enTitle),'description':b(esBody,enBody),'image':img(h['mediaUrl']),'source':source})
testEs=['Jarosław Orłowski describe cómo BellaBot atrae la atención de los comensales y aporta una experiencia distinta al restaurante.','Dariusz Oleksiak destaca el apoyo al personal y la buena recepción de los robots entre los huéspedes.','Zeng Xianghui explica que el apoyo de PuduBot libera tiempo para aprender otras tareas del restaurante.','Fran Benavides señala que el traslado de platos permite al equipo dedicar más atención al cliente.','Yoshimura describe menos desplazamientos para entregar artículos y más tiempo disponible para los residentes.','Yukari Yamamoto relata una reducción del tiempo dedicado a aspirar y trapear, con más atención al huésped.','Katarzyna Chajec destaca el apoyo en recepción y el uso de la pantalla para información interna.','Zhang Jie comenta el apoyo de PuduBot al ritmo del servicio y el interés que despierta entre los visitantes.']
testEn=['Jarosław Orłowski describes BellaBot attracting diners’ attention and adding a distinctive restaurant experience.','Dariusz Oleksiak highlights staff assistance and guests’ positive reception of the robots.','Zeng Xianghui explains that PuduBot support frees time to learn other restaurant tasks.','Fran Benavides notes that moving dishes allows the team to dedicate more attention to customers.','Yoshimura describes fewer item-delivery trips and more time available for residents.','Yukari Yamamoto reports less time spent vacuuming and mopping, allowing more guest interaction.','Katarzyna Chajec highlights reception assistance and on-screen internal information.','Zhang Jie discusses PuduBot’s support for service flow and the interest it sparks among visitors.']
testimonials=[{'brand':h['title'],'person':h['secondTitle'].split(',')[0],'text':b(es,en),'image':img(h['mediaUrl']),'source':'https://www.pudurobotics.com/en'} for h,es,en in zip(home['cards'],testEs,testEn)]
# Original Botmate explainers based on specific official resources.
articles=[
('como-elegir-amr','Cómo elegir un AMR para tu almacén','How to choose a warehouse AMR','warehouse-amr-selection-guide-logistics','Antes del robot, define el recorrido.','Define the route before choosing the robot.','Documenta qué se mueve, cuánto pesa, cómo se carga y con qué frecuencia viaja. Esa información permite comparar un robot de reparto industrial con una solución de manejo de tarimas.','Document what moves, how much it weighs, how it is loaded and how often it travels. This helps compare an industrial delivery robot with a pallet-handling solution.','En la evaluación del sitio, revisa anchos, cruces, cambios de piso, puertas, tráfico de personas y puntos de carga. La capacidad nominal del robot no sustituye la revisión de todo el recorrido.','During the site assessment, check aisle widths, intersections, floor transitions, doors, pedestrian traffic and charging points. Payload ratings do not replace a full route review.'),
('amr-vs-agv','AMR o AGV: empieza por tu operación','AMR or AGV: start with your operation','amr-vs-agv-automotive-parts-manufacturing','No todas las rutas necesitan la misma automatización.','Not every route needs the same automation.','El recurso de Pudu compara enfoques de transporte automatizado en manufactura automotriz. Para seleccionar una solución, considera cuánto cambia el entorno y cómo se integrará con tus procesos existentes.','Pudu’s resource compares automated transport approaches in automotive manufacturing. When selecting a solution, consider how often the environment changes and how it integrates with existing processes.','Prepara una prueba con una carga representativa y mide los tiempos de recorrido, las intervenciones y las esperas. Estos datos ayudan a evaluar la solución dentro de tu instalación.','Prepare a trial with a representative load and measure travel times, interventions and waiting. These observations help assess the solution within your facility.'),
('limpieza-espacios-pequenos','Limpieza robótica en espacios pequeños','Robotic cleaning in smaller spaces','pudu-et1-ai-native-compact-scrubber-dryer-robot','Un espacio compacto también merece atención.','Compact spaces deserve attention too.','Pudu presentó ET1 para espacios comerciales pequeños, con una referencia de aplicación de 100 a 800 m². Es una categoría para explorar en tiendas de conveniencia, restaurantes, hoteles y oficinas.','Pudu introduced ET1 for smaller commercial spaces, with a stated application range of 100 to 800 m². This category can be explored for convenience stores, restaurants, hotels and offices.','El área total es sólo el inicio: también importan el tipo de piso, el mobiliario, la suciedad y la ubicación de la estación. Solicita una evaluación antes de definir la configuración.','Total area is only the starting point: floor type, furniture, dirt and station placement also matter. Request an assessment before defining the configuration.'),
('robots-industria-textil','Robots en la industria textil','Robots in textile manufacturing','pudu-robotics-textile-manufacturing-cleaning-logistics','Limpieza y logística pueden avanzar juntas.','Cleaning and logistics can move together.','Pudu publica aplicaciones de robótica en empresas textiles, combinando cuidado de superficies y movimiento de materiales. La selección del equipo parte de la tarea concreta que necesita apoyo.','Pudu publishes robotics applications in textile companies, combining surface care and material movement. Equipment selection starts with the specific task that needs support.','En Botmate, el siguiente paso es revisar el flujo de materiales, las superficies y las necesidades de limpieza para proponer un piloto con criterios de evaluación definidos.','At Botmate, the next step is to review material flows, surfaces and cleaning needs to propose a pilot with defined evaluation criteria.'),
('ia-fisica-pudu','IA física: del software al trabajo en el mundo real','Physical AI: from software to real-world work','pudu-robotics-unveils-pudufm-1-0-embodied-intelligence-foundation-model','Una nueva categoría de posibilidades.','A new category of possibilities.','Pudu presenta PuduFM 1.0 como parte de su trabajo en inteligencia incorporada. Su catálogo incluye robots móviles, cuadrúpedos y humanoides para explorar diferentes tareas.','Pudu presents PuduFM 1.0 as part of its work in embodied intelligence. Its portfolio includes mobile, quadruped and humanoid robots for exploring different tasks.','Una demostración tecnológica no equivale a una implementación lista para cualquier negocio. Para un proyecto en México, confirma disponibilidad, funciones soportadas y alcance de integración con Botmate.','A technology demonstration is not a ready-made deployment for every business. For a project in Mexico, confirm availability, supported functions and integration scope with Botmate.'),
]
posts=[]
for slug,et,nt,key,eh,nh,eb,nb,eb2,nb2 in articles:
 src=json.loads((R/'.pudu-source'/('en_news_'+key+'.json')).read_text());news=next((x for x in home.get('news',[])+home.get('topNews',[]) if x.get('docPath')==key),{});media=news.get('mediaUrl') or next((x for x in src.get('media',[]) if x.endswith('.webp')),home['messages']['mediaUrl']);posts.append({'slug':slug,'title':b(et,nt),'intro':b(eh,nh),'paragraphs':[b(eb,nb),b(eb2,nb2)],'image':img(media),'source':src['url'],'date':'2026-09-13'})
(R/'lib/pudu-catalog.json').write_text(json.dumps(d,ensure_ascii=False,indent=2));(R/'lib/pudu-stories.json').write_text(json.dumps({'cases':cases,'testimonials':testimonials,'posts':posts},ensure_ascii=False,indent=2));(R/'docs/pudu/web-media-jobs.json').write_text(json.dumps(list({x['url']:x for x in jobs}.values()),ensure_ascii=False,indent=2));print({'cases':len(cases),'testimonials':len(testimonials),'posts':len(posts)})
