import json,pathlib
R=pathlib.Path(__file__).resolve().parents[1];p=R/'lib/pudu-catalog.json';d=json.loads(p.read_text())
def b(es,en=None):return {'es':es,'en':en or es}
def row(es,en,value,valueen=None):return {'label':b(es,en),'value':b(value,valueen)}
manual={
'bellabot-pro':[row('Carga máxima','Maximum payload','40 kg (10 kg por bandeja)','40 kg (10 kg per tray)'),row('Dimensiones','Dimensions','57 × 55 × 129 cm'),row('Autonomía sin carga','Unloaded runtime','11 h'),row('Tiempo de carga','Charging time','4.5 h'),row('Paso mínimo','Minimum passage','65 cm')],
'pudu-cc1-pro':[row('Funciones','Cleaning functions','Barrido, aspirado, trapeado y fregado','Sweeping, vacuuming, dust mopping and scrubbing'),row('Tanques de agua','Water tanks','15 L limpia / 15 L residual','15 L clean / 15 L waste'),row('Dimensiones','Dimensions','629 × 552 × 695 mm'),row('Autonomía de referencia','Reference runtime','5 h fregado / 9 h trapeado silencioso','5 h scrubbing / 9 h silent mopping'),row('Tiempo de carga','Charging time','Aproximadamente 3 h','About 3 h')],
'flashbot-max':[row('Carga por compartimento','Payload per compartment','10 kg'),row('Compartimentos','Compartments','2–4, configurables','2–4, configurable'),row('Dimensiones','Dimensions','538 × 534 × 1052 mm'),row('Autonomía de referencia','Reference runtime','9 h'),row('Tiempo de carga','Charging time','4 h')],
'pudu-sh1':[row('Operación','Operation','Con operador','Operator-guided'),row('Dimensiones','Dimensions','49 × 53 × 120 cm'),row('Peso','Weight','17 kg'),row('Tanques de agua','Water tanks','4 L limpia / 4 L residual','4 L clean / 4 L waste'),row('Autonomía de referencia','Reference runtime','70 min estándar / 100 min ECO','70 min standard / 100 min ECO'),row('Tiempo de carga','Charging time','2.5 h')],
'pudu-t300':[row('Carga máxima','Maximum payload','300 kg'),row('Versión de referencia','Reference version','T300 Standard · WTID01'),row('Peso','Weight','65 kg'),row('Paso mínimo','Minimum passage','≥60 cm'),row('Autonomía con carga completa','Runtime at full load','8 h'),row('Tiempo de carga','Charging time','2 h')],
'pudu-mt1':[row('Funciones','Functions','Barrido autónomo con IA','AI-powered autonomous sweeping'),row('Dimensiones','Dimensions','840 × 600 × 490 mm'),row('Depósito de residuos','Waste bin','35 L'),row('Autonomía según nivel de limpieza','Runtime by cleaning level','4–8 h'),row('Tiempo de carga','Charging time','<3 h')],
'flashbot-arm':[row('Tipo','Type','Robot semihumanoide de servicio','Semi-humanoid service robot'),row('Dimensiones','Dimensions','539 × 515 × 1440 mm'),row('Capacidad publicada','Published capacity','15 kg'),row('Autonomía sin carga','Unloaded runtime','8 h'),row('Tiempo de carga','Charging time','4 h'),row('Paso mínimo','Minimum passage','65 cm')],
'pudu-d9':[row('Altura','Height','170 cm'),row('Peso','Weight','65 kg'),row('Grados de libertad totales','Total degrees of freedom','42'),row('Carga en entorno de prueba','Payload in test environment','20 kg (10 kg por brazo)','20 kg (10 kg per arm)'),row('Batería','Battery','15 Ah (0.72 kWh)')],
'pudu-d5-series':[row('Variantes de la familia','Family variants','D5 / D5-W'),row('Dimensiones de pie','Standing dimensions','900 × 543 × 572 mm'),row('Peso con batería','Weight with battery','56 kg'),row('Batería','Battery','1,000 Wh'),row('Autonomía por versión','Runtime by version','D5: 2–2.5 h / D5-W: 2–3 h')],
'pudu-d7':[row('Generación de referencia','Reference generation','D7 industrial · lanzamiento junio 2026','Industrial D7 · June 2026 launch'),row('Tipo','Type','Robot semihumanoide industrial','Industrial semi-humanoid robot'),row('Carga publicada','Published payload','Hasta 14 kg','Up to 14 kg'),row('Altura de operación publicada','Published operating height','Hasta 2 m','Up to 2 m'),row('Modelo de IA del fabricante','Manufacturer AI model','PuduFM 1.0')],
}
labels={'Model Number':'Modelo','Machine Dimensions':'Dimensiones','Machine Weight':'Peso','Lifting Height':'Altura de elevación','Maximum load':'Carga máxima','Battery Capacity':'Capacidad de batería','Charging Time':'Tiempo de carga','Operating Time':'Autonomía','Machine Size':'Dimensiones','Loading Capacity':'Capacidad de carga','Run-time':'Autonomía','Cruise Speed':'Velocidad de desplazamiento','Clearance':'Paso mínimo','AD Display Size':'Pantalla publicitaria','Machine Material':'Materiales','Battery Life':'Autonomía','Load Capacity':'Capacidad de carga','Tray Size':'Dimensiones de bandeja','Robot Weight':'Peso','Safety':'Velocidad y pendiente'}
replacements={'no-load operation':'operación sin carga','no-load':'sin carga','None load':'sin carga','none load':'sin carga','in specific situations':'en condiciones específicas','inches':'pulgadas','pounds':'libras','layer':'nivel','tray':'bandeja','Speed':'Velocidad','Adjustable':'ajustable','Climbing angle':'Ángulo de subida','aircraft-grade aluminum alloy':'aleación de aluminio de grado aeronáutico'}
for r in d['products']:
 if r['slug'] in manual:r['specs']=manual[r['slug']]
 for s in r['specs']:
  s['label']['es']=labels.get(s['label']['es'],s['label']['es'])
  for en,es in replacements.items():s['value']['es']=s['value']['es'].replace(en,es)
 r['features']['en']=[x.replace('24/7 Continuous Operation','Continuous operation with charging support') for x in r['features']['en']]
p.write_text(json.dumps(d,ensure_ascii=False,indent=2))
