import {botmateCases} from '@/lib/botmate-cases';
import {BotmateClients,BotmateCaseCards,BotmateArchive,BotmateCaseDetail} from '@/components/BotmateCases';
import {FinderPage,SupportPage,FAQPage} from '@/components/DecisionPages';
import {legacyEnglishPosts,legacyEnglishRobots} from '@/lib/legacy-en';
import {LegacyEnglishArticle,LegacyEnglishRobot} from '@/components/LegacyEnglish';
import FieldGallery from '@/components/FieldGallery';
import {notFound,permanentRedirect} from 'next/navigation';
import {PuduHome,PuduIntro,PuduCTA,PuduIndustries,PuduCaseCards,PuduProductDetail} from '@/components/PuduSections';
import {IndustryDetail,CaseDetail,PartsPage,BlogPage,BlogDetail,AboutPage,ResourcesPage,EnglishServicePage,EnglishBooking,EnglishContact} from '@/components/PuduPages';
import PuduCatalog from '@/components/PuduCatalog';
import {puduProducts,puduIndustries,puduAliases} from '@/lib/pudu';
import stories from '@/lib/pudu-stories.json';
import {spanishPath} from '@/lib/locale';
import {localizedMetadata} from '@/lib/pudu-seo';
type Props={params:Promise<{path?:string[]}>;searchParams:Promise<{familia?:string;robot?:string}>};
const pages:Record<string,[string,string]>={
 '':['Pudu robots in Mexico · Botmate, official distributor','Explore Pudu robots for cleaning, delivery, industrial logistics and physical AI. Discover models, industries, international cases and Botmate support in Mexico.'],
 robots:['Pudu robot catalog in Mexico','Compare 27 Pudu models and variants for your business in Mexico.'],
 industries:['Robotics solutions for 11 application areas','Explore Pudu applications for hospitality, retail, manufacturing, healthcare, transportation, education and public spaces.'],
 'case-studies':['Botmate projects in Mexico and Pudu case studies','Explore Botmate projects with Walmart, Purina, Mabe and Meximold, their documented scope and international Pudu references.'],
 'find-your-robot':['Find your robot in Mexico · Botmate selector','Explore robots by task and prepare your project. Assess transport workload for your business in Mexico.'],
 support:['Robot support in Mexico · Botmate','Prepare a request for diagnosis, maintenance, training and robot spare parts with Botmate.'],
 faq:['Robot rental, purchase and support FAQ · Botmate','Answers about pricing, rental, purchases, demonstrations, installation, warranty and support in Mexico.'],
 'spare-parts':['Pudu accessories and spare parts','Explore official Pudu accessories and check model compatibility with Botmate.'],
 blog:['Robotics insights and guides','Botmate guides based on official Pudu resources.'],
 about:['Botmate · Official Pudu Robotics distributor in Mexico','Global robotics technology and local project conversations with Botmate.'],
 resources:['Pudu brochures, datasheets and resources','Explore the official Pudu resource library.'],
 book:['Book a call with Botmate','Choose a time to discuss your robotics project in Mexico.'],
 contact:['Contact Botmate','Talk to Botmate about robots, applications, availability and support.'],
 services:['Robot implementation and support','Explore project assessment, configuration and implementation with Botmate.'],
 rental:['Robot rental in Mexico','Explore robots for events, activations and projects with Botmate.'],
 purchase:['Buy Pudu robots in Mexico','Explore Pudu robot purchases and implementation with Botmate.'],
 privacy:['Privacy and data','How this website connects you to Botmate and third-party services.'],
};
export async function generateMetadata({params}:Props){const {path=[]}=await params;const [section='',slug]=path;const caseImage=section==='case-studies'?botmateCases.find(c=>c.slug===slug):undefined;let details: [string,string] | undefined=pages[section];if(slug){const p=section==='robots'?puduProducts.find(r=>r.slug===slug):null;const i=section==='industries'?puduIndustries.find(r=>r.slug===slug):null;const own=section==='case-studies'?botmateCases.find(r=>r.slug===slug):null;const c=section==='case-studies'?stories.cases.find(r=>r.slug===slug):null;const b=section==='blog'?stories.posts.find(r=>r.slug===slug):null;const oldPost=section==='blog'?legacyEnglishPosts.find(p=>p.slug===slug):null;const oldRobot=section==='robots'?legacyEnglishRobots.find(p=>p.slug===slug):null;details=own?[own.brand+' · Botmate project in Mexico',own.description.en]:oldPost?[oldPost.title,oldPost.excerpt]:oldRobot?[oldRobot.name,oldRobot.description]:p?[p.name+' in Mexico',p.name+': '+p.description.en]:i?[i.title.en,i.description.en]:c?[c.brand+" · Pudu case study",c.title.en]:b?[b.title.en,b.intro.en]:undefined;}if(section==='privacy')return {...localizedMetadata('Privacy and data','How this website connects you to Botmate and third-party services.','/privacidad','en'),robots:{index:false,follow:true}};return details?.length?localizedMetadata(details[0],details[1],spanishPath('/en'+(path.length?'/'+path.join('/'):'')),'en',caseImage?{url:caseImage.image,alt:caseImage.imageAlt.en}:undefined):{};}
export default async function Page({params,searchParams}:Props){const {familia,robot}=await searchParams;const {path=[]}=await params;const [section='',slug]=path;if(path.length>2)notFound();if(slug){const oldPost=section==='blog'?legacyEnglishPosts.find(p=>p.slug===slug):null;const oldRobot=section==='robots'?legacyEnglishRobots.find(p=>p.slug===slug):null;if(oldPost)return <LegacyEnglishArticle post={oldPost}/>;if(oldRobot)return <LegacyEnglishRobot robot={oldRobot}/>;if(section==='robots'){if(puduAliases[slug])permanentRedirect('/en/robots/'+puduAliases[slug]);const r=puduProducts.find(r=>r.slug===slug);if(r)return <PuduProductDetail robot={r} locale="en"/>;}if(section==='industries'){const r=puduIndustries.find(r=>r.slug===slug);if(r)return <IndustryDetail industry={r} locale="en"/>;}if(section==='case-studies'){const own=botmateCases.find(r=>r.slug===slug);if(own)return <BotmateCaseDetail entry={own} locale="en"/>;const r=stories.cases.find(r=>r.slug===slug);if(r)return <CaseDetail entry={r} locale="en"/>;}if(section==='blog'){const r=stories.posts.find(r=>r.slug===slug);if(r)return <BlogDetail post={r} locale="en"/>;}notFound();}
 switch(section){case 'find-your-robot':return <FinderPage locale="en"/>;case 'support':return <SupportPage locale="en"/>;case 'faq':return <FAQPage locale="en"/>;case '':return <PuduHome locale="en"/>;case 'robots':return <><PuduIntro locale="en" eyebrow="Pudu Robotics catalog" title="The robot for your next move." description="27 models and variants. Explore families, compare applications and discuss the right configuration for your business in Mexico."/><section className="container-x section-space section-compact"><PuduCatalog locale="en" initialCategory={familia}/><p className="pudu-attribution">Pudu’s global portfolio. Botmate confirms availability, versions and implementation scope for Mexico.</p></section><PuduCTA locale="en"/></>;case 'industries':return <><PuduIntro locale="en" eyebrow="Solutions by industry" title="Your industry. New possibilities." description="Explore applications across eleven application areas, with official Pudu imagery and models to evaluate with Botmate."/><PuduIndustries locale="en"/><PuduCTA locale="en"/></>;case 'case-studies':return <><PuduIntro locale="en" eyebrow="Projects and case studies" title="Technology connecting brands and people." description="Botmate projects in Mexico, brand archives and international Pudu references. Each profile identifies its scope and status."/><BotmateClients locale="en"/><BotmateCaseCards locale="en"/><BotmateArchive locale="en"/><PuduCaseCards locale="en"/><FieldGallery locale="en"/><PuduCTA locale="en"/></>;case 'spare-parts':return <PartsPage locale="en"/>;case 'blog':return <BlogPage locale="en"/>;case 'about':return <AboutPage locale="en"/>;case 'resources':return <ResourcesPage locale="en"/>;case 'book':return <EnglishBooking/>;case 'contact':return <EnglishContact robot={robot}/>;case 'services':case 'rental':case 'purchase':return <EnglishServicePage kind={section}/>;case 'privacy':return <><PuduIntro locale="en" eyebrow="Privacy & data" title="Your information, with context." description="Botmate uses the information you choose to share to respond to project enquiries."/><section className="container-x pudu-editorial section-space"><p>Opening the booking calendar loads Google Calendar. Completing a booking is handled by Google and its privacy terms. WhatsApp and email links open external services; you decide what information to send.</p><p>Robot images and videos are served from this website. Animation preferences are stored for the browser session. Contact contacto@botmate.mx for questions about your information.</p><p>This page describes the website’s functionality. The complete legal privacy notice is pending review by Botmate.</p></section></>;default:notFound();}}
